/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vehiclesofinterestdesktop;

import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Brian
 */
public class JF_ManageVOI extends javax.swing.JFrame {

    /**
     * Creates new form JF_ManageVOI
     */
    public JF_ManageVOI() {
        initComponents();
        setLocationRelativeTo(null);
        this.clearAllInputs();
        this.populateCB();
        
        //This indicates that the window is creating a new VOI
        windowState=0;
    }

    public JF_ManageVOI(String licensePlate, String reason, String make, String model, String veh_year, String color, String ownersName, String ownersPhone) {
        initComponents();
        setLocationRelativeTo(null);
        
        //This indicates that the window is creating a new VOI
        this.clearAllInputs();
        windowState=1;

        //Setting the text fields first
        jTF_LicensePlateNumber.setText(licensePlate);
        jTF_Year.setText(veh_year);
        jTF_Color.setText(color);
        jTF_OwnersName.setText(ownersName);
        jTF_OwnersPhone.setText(ownersPhone);

        //Selecting the correct drop down options
        this.populateCB();
        
        jCB_AlertType.setSelectedItem(reason.trim());
        jCB_VehicleMake.setSelectedItem(make);
        jCB_VehicleModel.setSelectedItem(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_AlertType = new javax.swing.JLabel();
        jCB_AlertType = new javax.swing.JComboBox<>();
        jL_LicensePlate = new javax.swing.JLabel();
        jTF_LicensePlateNumber = new javax.swing.JTextField();
        jL_VehicleMake = new javax.swing.JLabel();
        jCB_VehicleMake = new javax.swing.JComboBox<>();
        jL_VehicleModel = new javax.swing.JLabel();
        jCB_VehicleModel = new javax.swing.JComboBox<>();
        jL_Year = new javax.swing.JLabel();
        jTF_Year = new javax.swing.JTextField();
        jL_Color = new javax.swing.JLabel();
        jTF_Color = new javax.swing.JTextField();
        jL_OwnersName = new javax.swing.JLabel();
        jTF_OwnersName = new javax.swing.JTextField();
        jL_OwnersPhone = new javax.swing.JLabel();
        jTF_OwnersPhone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbtDone = new javax.swing.JButton();
        jbtCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vehicle of Interest");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                windowFirstOpens(evt);
            }
        });

        jL_AlertType.setText("Alert Type");

        jCB_AlertType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCB_AlertType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_AlertTypeActionPerformed(evt);
            }
        });

        jL_LicensePlate.setText("License Plate Number");

        jTF_LicensePlateNumber.setText("jTextField1");

        jL_VehicleMake.setText("Vehicle Make");

        jCB_VehicleMake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCB_VehicleMake.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                makeChanged(evt);
            }
        });

        jL_VehicleModel.setText("Vehicle Model");

        jCB_VehicleModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jL_Year.setText("Year");

        jTF_Year.setText("jTextField1");

        jL_Color.setText("Color");

        jTF_Color.setText("jTextField1");

        jL_OwnersName.setText("Owners Name");

        jTF_OwnersName.setText("jTextField2");

        jL_OwnersPhone.setText("Owners Phone");

        jTF_OwnersPhone.setText("jTextField3");

        jLabel1.setText("*= Optional Field");

        jbtDone.setText("Done");
        jbtDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDoneActionPerformed(evt);
            }
        });

        jbtCancel.setText("Cancel");
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jL_Year, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_VehicleModel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_Color, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_OwnersName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_OwnersPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtDone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_LicensePlate)
                            .addComponent(jL_AlertType)
                            .addComponent(jL_VehicleMake))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCB_VehicleMake, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCB_AlertType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTF_LicensePlateNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(jCB_VehicleModel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTF_Year)
                            .addComponent(jTF_Color)
                            .addComponent(jTF_OwnersName)
                            .addComponent(jTF_OwnersPhone))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                        .addComponent(jbtCancel)
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCB_AlertType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_AlertType))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_LicensePlate)
                    .addComponent(jTF_LicensePlateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCB_VehicleMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_VehicleMake))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_VehicleModel)
                    .addComponent(jCB_VehicleModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Year)
                    .addComponent(jTF_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Color))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_OwnersName)
                    .addComponent(jTF_OwnersName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_OwnersPhone)
                    .addComponent(jTF_OwnersPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtDone)
                    .addComponent(jbtCancel))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelActionPerformed
        super.dispose();
    }//GEN-LAST:event_jbtCancelActionPerformed

    private void windowFirstOpens(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowFirstOpens
        //Housekeeping methods to clear and populate the CB's
        //this.populateCB();

    }//GEN-LAST:event_windowFirstOpens

    private void jCB_AlertTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_AlertTypeActionPerformed
        String selectedReason = (String) jCB_AlertType.getSelectedItem();
     }//GEN-LAST:event_jCB_AlertTypeActionPerformed

    private void makeChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_makeChanged
        jCB_VehicleModel.removeAllItems();
        JF_ManageMakeModel makeModel = new JF_ManageMakeModel();

        //Retrieve whatever the new selected make is
        String selectedMake = jCB_VehicleMake.getItemAt(jCB_VehicleMake.getSelectedIndex());

        //Prepare an arraylist to accept the models from the MakeModel Class
        ArrayList<String> models = new ArrayList<String>();
        models = makeModel.getSpecificModel(selectedMake);
        for (int x = 0; x < models.size(); x++) {
            jCB_VehicleModel.addItem(models.get(x));
        }
    }//GEN-LAST:event_makeChanged

    private void jbtDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDoneActionPerformed
        String reason = null;
        String licensePlate = null;
        String make = null;
        String model = null;
        String veh_year = jTF_Year.getText();
        String color = jTF_Color.getText();
        String ownersName = jTF_OwnersName.getText();
        String ownersPhone = jTF_OwnersPhone.getText();

        try {
            reason = jCB_AlertType.getSelectedItem().toString();
            licensePlate = jTF_LicensePlateNumber.getText();
            make = jCB_VehicleMake.getSelectedItem().toString();
            model = jCB_VehicleModel.getSelectedItem().toString();

        } catch (Exception e) {

        }

        //Error Missing Alert Type, License Plate No., Make or Model
        if ((reason == "" || reason == null)
                || (licensePlate.length() < 1 || licensePlate == null)
                || (make == "" || make == null)
                || (model == "" || model == null)) {
            JOptionPane.showMessageDialog(this,"Missing required field");
        } else if (reason.length() > 0
                && licensePlate.length() >= 1
                && make.length() > 0
                && model.length() > 0) {
            if (windowState == 0) {
                voi_c.createVehicleOfInterest(licensePlate, reason, make, model, veh_year, color, ownersName, ownersPhone);
                JOptionPane.showMessageDialog(this,"Added a VOI!");
            } else if (windowState==1) {
                voi_c.updateVehicleOfInterest(licensePlate, reason, make, model, veh_year, color, ownersName, ownersPhone);
                JOptionPane.showMessageDialog(this,"Updated a VOI!");
            }

            this.clearAllInputs();
            super.dispose();
        }

    }//GEN-LAST:event_jbtDoneActionPerformed

    /**
     * @param args the command line arguments
     */
    private void clearAllInputs() {
        jCB_AlertType.removeAllItems();
        jCB_VehicleMake.removeAllItems();
        jCB_VehicleModel.removeAllItems();

        jTF_Color.setText("");
        jTF_LicensePlateNumber.setText("");
        jTF_OwnersName.setText("");
        jTF_OwnersPhone.setText("");
        jTF_OwnersPhone.setText("");
        jTF_Year.setText("");

    }

    private void populateCB() {
        //Populating the Alert Types
        String[] reasons = voi_c.allReasonsForInterestKey();

        for (int x = 0; x < reasons.length; x++) {
            jCB_AlertType.addItem(reasons[x]);
        }

        //Populate the Vehicle Makes (Models will be updated as makes are selected)
        String[] makes = voi_c.allVehicleMakeKey();
        for (int x = 0; x < makes.length; x++) {
            jCB_VehicleMake.addItem(makes[x]);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_ManageVOI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_ManageVOI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_ManageVOI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_ManageVOI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_ManageVOI().setVisible(true);
            }
        });
    }

    private VehiclesOfInterestController voi_c = new VehiclesOfInterestController();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCB_AlertType;
    private javax.swing.JComboBox<String> jCB_VehicleMake;
    private javax.swing.JComboBox<String> jCB_VehicleModel;
    private javax.swing.JLabel jL_AlertType;
    private javax.swing.JLabel jL_Color;
    private javax.swing.JLabel jL_LicensePlate;
    private javax.swing.JLabel jL_OwnersName;
    private javax.swing.JLabel jL_OwnersPhone;
    private javax.swing.JLabel jL_VehicleMake;
    private javax.swing.JLabel jL_VehicleModel;
    private javax.swing.JLabel jL_Year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTF_Color;
    private javax.swing.JTextField jTF_LicensePlateNumber;
    private javax.swing.JTextField jTF_OwnersName;
    private javax.swing.JTextField jTF_OwnersPhone;
    private javax.swing.JTextField jTF_Year;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtDone;
    // End of variables declaration//GEN-END:variables
    //this will tell me if I am creating a voi (window state 0), or editing a VOI (window state 1)
    private int windowState;
}
