/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vehiclesofinterestdesktop;

/**
 *
 * @author Brian
 */
public class JF_ManageMakeModel extends javax.swing.JFrame {

    /**
     * Creates new form JF_ManageMakeModel
     */
    public JF_ManageMakeModel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Make = new javax.swing.JLabel();
        jCB_Make = new javax.swing.JComboBox<>();
        jL_Model = new javax.swing.JLabel();
        jCB_Model = new javax.swing.JComboBox<>();
        jL_Make2 = new javax.swing.JLabel();
        jTF_Make = new java.awt.TextField();
        jL_Model2 = new javax.swing.JLabel();
        jTF_Model = new java.awt.TextField();
        jbt_Create = new javax.swing.JButton();
        jbt_EditSelected = new javax.swing.JButton();
        jbt_DeleteSelected = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Make / Model");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                windowFirstOpens(evt);
            }
        });

        jL_Make.setText("Make");

        jCB_Make.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCB_Make.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                makeChanged(evt);
            }
        });
        jCB_Make.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changedMake(evt);
            }
        });

        jL_Model.setText("Model");

        jCB_Model.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jL_Make2.setText("Make");

        jTF_Make.setText("textField1");

        jL_Model2.setText("Model");

        jTF_Model.setText("textField2");

        jbt_Create.setText("Create");
        jbt_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_CreateActionPerformed(evt);
            }
        });

        jbt_EditSelected.setText("Edit Selected");

        jbt_DeleteSelected.setText("Delete Selected");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jL_Make)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCB_Make, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jL_Model, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCB_Model, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbt_Create)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(jbt_EditSelected)
                        .addGap(66, 66, 66)
                        .addComponent(jbt_DeleteSelected)
                        .addGap(30, 30, 30))))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_Make2)
                    .addComponent(jL_Model2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTF_Make, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTF_Model, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCB_Make, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB_Model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Make)
                    .addComponent(jL_Model))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_Make2)
                    .addComponent(jTF_Make, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTF_Model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Model2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_Create)
                    .addComponent(jbt_EditSelected)
                    .addComponent(jbt_DeleteSelected))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_CreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_CreateActionPerformed

    private void windowFirstOpens(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowFirstOpens
        // TODO add your handling code here:
        jCB_Make.removeAllItems();
        String[] make = voi_c.allVehicleMakeKey();
        for (int x = 0; x < make.length; x++) {
            jCB_Make.addItem(make[x]);
        }

        jCB_Model.removeAllItems();
    }//GEN-LAST:event_windowFirstOpens

    private void changedMake(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changedMake
        // TODO add your handling code here:
    }//GEN-LAST:event_changedMake

    private void makeChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_makeChanged
        //Clear all items from the model list because a new make was selected
        jCB_Model.removeAllItems();

        String[] allModels = voi_c.allVehicleModelKey();
        String[][] specificModels = voi_c.allVehicleModel();
        System.out.println(specificModels);

        for (int x = 0; x < specificModels[x][1].length(); x++) {
            //Commented out array diagnostics
            //Make
            System.out.print((String) specificModels[x][1] + ' ');
            //Model
            System.out.println((String) specificModels[x][0]);

            //This retrieves whatever make was selected from the dropdown
            String selectedMake = jCB_Make.getItemAt(jCB_Make.getSelectedIndex());

            //This reads the database table for make and add's the model to the list if the make matches
            if (specificModels[x][1].equalsIgnoreCase(selectedMake)) {
                jCB_Model.addItem(specificModels[x][0]);
            }
        }
        System.out.println("END");
    }//GEN-LAST:event_makeChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_ManageMakeModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_ManageMakeModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_ManageMakeModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_ManageMakeModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_ManageMakeModel().setVisible(true);
            }
        });
    }
    private VehiclesOfInterestController voi_c = new VehiclesOfInterestController();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCB_Make;
    private javax.swing.JComboBox<String> jCB_Model;
    private javax.swing.JLabel jL_Make;
    private javax.swing.JLabel jL_Make2;
    private javax.swing.JLabel jL_Model;
    private javax.swing.JLabel jL_Model2;
    private java.awt.TextField jTF_Make;
    private java.awt.TextField jTF_Model;
    private javax.swing.JButton jbt_Create;
    private javax.swing.JButton jbt_DeleteSelected;
    private javax.swing.JButton jbt_EditSelected;
    // End of variables declaration//GEN-END:variables
}
